[package]
name = "meshdrop-tui"
version.workspace = true
edition.workspace = true

[[bin]]
name = "meshdrop-tui"
path = "src/main.rs"

[dependencies]
ratatui = "0.30"
crossterm = "0.28"

clap = { version = "4", features = ["derive"] }
dialoguer = "0.11"

tokio = { workspace = true, features = ["rt-multi-thread", "net", "io-util", "sync", "fs", "time", "macros", "signal"] }
async-channel = { workspace = true }
log = { workspace = true }
env_logger = { workspace = true }
anyhow = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
uuid = { workspace = true }
sha2 = { workspace = true }
hex = { workspace = true }

meshdrop-core = { path = "../meshdrop-core" }
rust-i18n = { workspace = true }
